### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dashboardBtn' of undefined

### ISSUE THREAD

**Issue by Sharad30** [greyatom-edu-tech/greyatom-ftp-tree#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 4.4.20 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.3
**Thrown From**: [greyatom-tree-view](https://github.com/greyatom-edu-tech/greyatom-ftp-tree) package 1.3.24

### Stack Trace

Uncaught TypeError: Cannot read property 'dashboardBtn' of undefined

```
At /home/sharad30/.atom/packages/greyatom-tree-view/lib/views/tree-view.js:309

TypeError: Cannot read property 'dashboardBtn' of undefined
    at TreeView.module.exports.TreeView.attach (/packages/greyatom-tree-view/lib/views/tree-view.js:309:37)
    at /packages/greyatom-tree-view/lib/views/tree-view.js:287:12)
    at emitNone (events.js:91:20)
    at Client.emit (events.js:185:7)
    at /packages/greyatom-tree-view/lib/client.js:448:14)
    at /packages/greyatom-tree-view/lib/connectors/sftp.js:61:62
    at SFTPStream.onReady (/packages/greyatom-tree-view/node_modules/ssh2/lib/client.js:878:9)
    at SFTPStream.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at SFTPStream.emit (events.js:185:7)
    at SFTPStream._transform (/packages/greyatom-tree-view/node_modules/ssh2-streams/lib/sftp.js:356:14)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/packages/greyatom-tree-view/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/greyatom-tree-view/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/greyatom-tree-view/node_modules/ssh2-streams/lib/ssh.js:3444:10)
    at SSH2Stream._transform (/packages/greyatom-tree-view/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/greyatom-tree-view/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SSH2Stream.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -0:37.2.0 commit-live-welcome:show-dashboard (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:23.2.0 commit-live:connect-to-project (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:23.2.0 commit-live-welcome:hide (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:23.2.0 commit-live:change-project-title (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:23.2.0 commit-live:refill-tasks (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```

```

**Comment by smoolya17** [comment]
Steps to reproduce this code:

1. Open Commit.live
2. Run Toolbar Update Extension Update available option.
3. Error Reproduced

```
TypeError: Cannot read property 'dashboardBtn' of undefined
    at TreeView.module.exports.TreeView.attach (file:///C:/Users/smool/.atom/packages/greyatom-tree-view/lib/views/tree-view.js:309:37)
    at Client.<anonymous> (file:///C:/Users/smool/.atom/packages/greyatom-tree-view/lib/views/tree-view.js:287:12)
    at emitNone (events.js:91:20)
    at Client.emit (events.js:185:7)
    at ConnectorSFTP.<anonymous> (file:///C:/Users/smool/.atom/packages/greyatom-tree-view/lib/client.js:448:14)
    at file:///C:/Users/smool/.atom/packages/greyatom-tree-view/lib/connectors/sftp.js:61:62
    at SFTPStream.onReady (C:\Users\smool\.atom\packages\greyatom-tree-view\node_modules\ssh2\lib\client.js:878:9)
    at SFTPStream.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at SFTPStream.emit (events.js:185:7)
    at SFTPStream._transform (C:\Users\smool\.atom\packages\greyatom-tree-view\node_modules\ssh2-streams\lib\sftp.js:356:14)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (C:\Users\smool\.atom\packages\greyatom-tree-view\node_modules\ssh2-streams\lib\sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SFTPStream.Writable.write (_stream_writable.js:220:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at SSH2Stream.<anonymous> (C:\Users\smool\.atom\packages\greyatom-tree-view\node_modules\ssh2\lib\Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (C:\Users\smool\.atom\packages\greyatom-tree-view\node_modules\ssh2-streams\lib\ssh.js:3444:10)
    at SSH2Stream._transform (C:\Users\smool\.atom\packages\greyatom-tree-view\node_modules\ssh2-streams\lib\ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (C:\Users\smool\.atom\packages\greyatom-tree-view\node_modules\ssh2-streams\lib\ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at SSH2Stream.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```
I cannot work on any of my projects
